spring:
  profiles:
    active: ${APP_PROFILE:dev}  # Usa 'dev' como padrão se variável não estiver definida
  application:
    name: biblioteca-virtual
  datasource:
    url: jdbc:h2:mem:testdb  # Banco em memória para desenvolvimento
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8080
  servlet:
    context-path: /api