spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recria o schema a cada execução de teste
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR